# Generated by Django 6.0.1 on 2026-01-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_student'),
        ('students', '0002_remove_student_user_studentprofile_academicrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterUniqueTogether(
            name='academicrecord',
            unique_together={('student', 'semester')},
        ),
    ]
