# Generated by Django 6.0.1 on 2026-01-20 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='hotspot_ssid',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='qr_token',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
