# Generated by Django 6.0.1 on 2026-01-20 17:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendancerecord_status_and_more'),
        ('students', '0003_delete_student_alter_academicrecord_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'session')},
        ),
    ]
